version: '2.1'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: multi_tenants
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d multi_tenants" ]
      interval: 10s
      timeout: 5s
      retries: 3
